RepositoryServicePatternDemo/Models/ErrorViewModel.cs
using System;

namespace RepositoryServicePatternDemo.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RepositoryServicePatternDemo/Controllers/FinancialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RepositoryServicePatternDemo.Core.Services.Interfaces;

namespace RepositoryServicePatternDemo.Controllers
{
    public class FinancialController : Controller
    {
        private readonly IFinancialsService _financialService;

        public FinancialController(IFinancialsService financialService)
        {
            _financialService = financialService;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

RepositoryServicePatternDemo/Controllers/FoodController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RepositoryServicePatternDemo.Core.Services.Interfaces;

namespace RepositoryServicePatternDemo.Controllers
{
    public class FoodController : Controller
    {
        private readonly IFoodService _foodService;

        public FoodController(IFoodService foodService)
        {
            _foodService = foodService;
        }

        public IActionResult Index()
        {
            var itemsSold = _foodService.GetAllSold();
            return View(itemsSold);
        }
    }
}

RepositoryServicePatternDemo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using RepositoryServicePatternDemo.Core.Services.Interfaces;
using RepositoryServicePatternDemo.Models;

namespace RepositoryServicePatternDemo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RepositoryServicePatternDemo/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using RepositoryServicePatternDemo.Core.Services.Interfaces;

namespace RepositoryServicePatternDemo.Controllers
{
    public class TicketController : Controller
    {
        private readonly ITicketService _ticketService;

        public TicketController(ITicketService ticketService)
        {
            _ticketService = ticketService;
        }

        public IActionResult Index()
        {
            var tickets = _ticketService.GetAllSold();
            return View(tickets);
        }
    }
}

RepositoryServicePatternDemo/ViewComponents/FinancialStatsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using RepositoryServicePatternDemo.Core.Services.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RepositoryServicePatternDemo.ViewComponents
{
    public class FinancialStatsViewComponent : ViewComponent
    {
        private readonly IFinancialsService _financialService;

        public FinancialStatsViewComponent(IFinancialsService financialService)
        {
            _financialService = financialService;
        }

        public Task<IViewComponentResult> InvokeAsync()
        {
            var stats = _financialService.GetStats();
            return Task.FromResult<IViewComponentResult>(View(stats));
        }
    }
}

RepositoryServicePatternDemo/Views/Food/Index.cshtml
@model IEnumerable<RepositoryServicePatternDemo.Core.Models.FoodItem>
@{
    ViewData["Title"] = "Index";
}

<h1>Food Items Sold</h1>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.Name)</th>
            <th>@Html.DisplayNameFor(model => model.SalePrice)</th>
            <th>@Html.DisplayNameFor(model => model.UnitPrice)</th>
            <th>Profit Per Item</th>
            <th>@Html.DisplayNameFor(model => model.Quantity)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.SalePrice)</td>
                <td>@Html.DisplayFor(modelItem => item.UnitPrice)</td>
                <td>$@(item.SalePrice - item.UnitPrice)</td>
                <td>@Html.DisplayFor(modelItem => item.Quantity)</td>
            </tr>
        }
    </tbody>
</table>

RepositoryServicePatternDemo/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-left">
    <h1 class="display-4">Hiya everybody!</h1>
    <p>This demo project is intended to help show how to use the Repository Service Pattern.</p>
    <p>A few things to remember about this pattern:</p>
    <ul>
        <li>
            The lower layer of the pattern is the <strong>Repositories</strong>.  These classes only ever deal with one model object.
            Our model objects are FoodItem and Ticket, and consequently there are repositories for each.
        </li>
        <li>
            The upper layer of this pattern is the <strong>Service</strong> classes.  In this implementation, the Services inherit
            from the repositories and can implement their own methods.  The reason for this is that Services are where we put functionality
            which deals with multiple Model objects.
        </li>
    </ul>
    <p>The goal of this pattern is to maintain clear and obvious separation between the layers.</p>
    <p>NOTE: If you will never have functionality which needs to reference multiple Model objects, you can remove the Services layer.</p>
</div>

RepositoryServicePatternDemo/Views/Shared/Components/FinancialStats/Default.cshtml
@model RepositoryServicePatternDemo.Core.Models.FinancialStats

<ul>
    <li class="d-inline-block">
        <strong>@Html.DisplayNameFor(x => x.AverageFoodItemProfit)</strong>
        @Html.DisplayFor(x => x.AverageFoodItemProfit)
    </li>
    <li class="d-inline-block">
        <strong>@Html.DisplayNameFor(x => x.AverageTicketProfit)</strong>
        @Html.DisplayFor(x => x.AverageTicketProfit)
    </li>
</ul>

RepositoryServicePatternDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Repository Service Pattern Demo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Repository Service Pattern Demo</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Food" asp-action="Index">Food</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ticket" asp-action="Index">Tickets</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @await Component.InvokeAsync("FinancialStats")
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - ExceptionNotFound
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

RepositoryServicePatternDemo/Views/Ticket/Index.cshtml
@model IEnumerable<RepositoryServicePatternDemo.Core.Models.Ticket>

@{
    ViewData["Title"] = "Index";
}

<h1>Tickets Sold</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MovieName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SalePrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StudioCutPercentage)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProfitPerItem)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MovieName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SalePrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StudioCutPercentage)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProfitPerItem)
            </td>
        </tr>
}
    </tbody>
</table>